### ISSUE TITLE
Uncaught ReferenceError: CSV is not defined

### ISSUE THREAD

**Issue by rjmorris** [DrPaulBrewer/html5csv#11]
After the meteor compatibility commit, which includes the note "CSV is now declared as a global, but not with window.CSV", I get the following error when I try to load the library:
```
Uncaught ReferenceError: CSV is not defined
```
Changing it back to `window.CSV` fixes the problem. This happens on Chrome 45, Firefox 38, and IE 10.

**Comment by DrPaulBrewer** [comment]
When CSV fails to show up as a global, is the html5csv.js file being imported through any kind of  packaging system like requirejs, commonjs, etc... or only using a script tag?

**Comment by rjmorris** [comment]
Just a script tag.

**Comment by DrPaulBrewer** [comment]
Thanks for reporting this bug. 

 It was related to "use strict;" a Javascript switch for improving code quality, preventing bare globals like "CSV" from being initialized.  

For more info, see the commit and commit message.
